#\DeclareLyXModule{lyx.local / pxrubrica}
#DescriptionBegin
#Module for inserting ruby characters (https://en.wikipedia.org/wiki/Ruby_character)
#DescriptionEnd
# Author : Kenji Sato <mail@kenjisato.jp>

Format 66

Counter blanknum
End

Preamble
    \usepackage{pxrubrica}
EndPreamble

InsetLayout  "Flex:ルビ/ 和文"
    LyXType     custom
    Argument 1
      LabelString "オプション"
      Mandatory   0
      AutoInsert	0
      PassThru    true
    EndArgument
    Argument 2
      LabelString "ルビ"
      Mandatory   1
      AutoInsert  1
      PassThru    true
      ToolTip			"グループ区切りの例) と|やま, ひろ|しま"
    EndArgument
    Decoration  classic
    LabelString 和文ルビ
    LatexName   jrubySwap
    LatexType   command
    MultiPar        false
    ContentAsLabel  true
    PassThru        1
    Preamble
        \newcommand{\jrubySwap}[3][]{\jruby[#1]{#3}{#2}}
    EndPreamble
End

InsetLayout  "Flex:ルビ/ 欧文"
    LyXType     custom
    Argument 1
      LabelString "オプション"
      Mandatory   0
      AutoInsert	0
      PassThru    true
    EndArgument
    Argument 2
      LabelString "ルビ"
      Mandatory   1
      AutoInsert  1
      PassThru    true
    EndArgument
    Decoration  classic
    LabelString 欧文ルビ
    LatexName   arubySwap
    LatexType   command
    MultiPar        false
    ContentAsLabel  true
    PassThru        1
    Preamble
        \newcommand{\arubySwap}[3][]{\aruby[#1]{#3}{#2}}
    EndPreamble
End

InsetLayout  "Flex:ルビ/ 和文両側"
    LyXType     custom
    Argument 1
      LabelString "オプション"
      Mandatory   0
      AutoInsert	0
      PassThru    true
    EndArgument
    Argument 2
      LabelString "ルビ1"
      Mandatory   1
      AutoInsert  1
      PassThru    true
      ToolTip			"注意! ルビ2を手動で追加してください。"
    EndArgument
    Argument 3
      LabelString "ルビ2"
      Mandatory   1
      AutoInsert  1
      PassThru    true
    EndArgument
    Decoration  classic
    LabelString 和文両側ルビ
    LatexName   trubySwap
    LatexType   command
    MultiPar        false
    ContentAsLabel  true
    PassThru        1
    Preamble
        \newcommand{\trubySwap}[4][]{\truby[#1]{#4}{#2}{#3}}
    EndPreamble
End

InsetLayout  "Flex:ルビ/ 欧文両側"
    LyXType     custom
    Argument 1
      LabelString "オプション"
      Mandatory   0
      AutoInsert	0
      PassThru    true
    EndArgument
    Argument 2
      LabelString "ルビ1"
      Mandatory   1
      AutoInsert  1
      PassThru    true
    EndArgument
    Argument 3
      LabelString "ルビ2"
      Mandatory   1
      AutoInsert  1
      PassThru    true
    EndArgument
    Decoration  classic
    LabelString 欧文両側ルビ
    LatexName   atrubySwap
    LatexType   command
    MultiPar        false
    ContentAsLabel  true
    PassThru        1
    Preamble
        \newcommand{\atrubySwap}[4][]{\atruby[#1]{#4}{#2}{#3}}
    EndPreamble
End

InsetLayout  "Flex:ルビ/ 圏点"
    LyXType     custom
    Argument 1
      LabelString "オプション"
      Mandatory   0
      AutoInsert	0
      PassThru    true
    EndArgument
    Decoration  classic
    LabelString 圏点
    LatexName   kenten
    LatexType   command
    MultiPar        false
    ContentAsLabel  true
End
